# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.CharField(max_length=16)),
                ('sn', models.CharField(max_length=16)),
                ('type', models.CharField(choices=[('F', 'Fermenter'), ('K', 'Keezer')], max_length=1)),
            ],
        ),
    ]
