# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fermenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(default=None, max_length=16)),
                ('dev', models.CharField(blank=True, default=None, max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Keezer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(default=None, max_length=16)),
                ('dev', models.CharField(blank=True, default=None, max_length=12)),
            ],
        ),
    ]
