# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fermenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=16)),
                ('dev', models.CharField(default='', max_length=12)),
                ('mode', models.CharField(default='CHILL', max_length=12)),
                ('setpoint', models.DecimalField(decimal_places=2, default=64.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Keezer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=16)),
                ('dev', models.CharField(max_length=12)),
            ],
        ),
    ]
