# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fermenter',
            name='mode',
            field=models.CharField(choices=[('C', 'CHILL'), ('H', 'HEAT')], default='C', max_length=1),
        ),
    ]
