# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fermenter',
            name='dev',
            field=models.CharField(blank=True, default=None, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='keezer',
            name='dev',
            field=models.CharField(blank=True, default=None, max_length=12, null=True),
        ),
    ]
