# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fermenter',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='keezer',
            name='tag',
        ),
        migrations.AddField(
            model_name='fermenter',
            name='sn',
            field=models.CharField(default=None, max_length=16),
        ),
        migrations.AddField(
            model_name='keezer',
            name='sn',
            field=models.CharField(default=None, max_length=16),
        ),
    ]
