# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_auto_20160225_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='fermenter',
            name='hysteresis',
            field=models.DecimalField(decimal_places=1, default=0.1, max_digits=2),
        ),
        migrations.AddField(
            model_name='fermenter',
            name='pumpdelay',
            field=models.IntegerField(default=60000),
        ),
        migrations.AddField(
            model_name='fermenter',
            name='pumprun',
            field=models.IntegerField(default=5000),
        ),
    ]
