# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 18:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_auto_20160224_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fermenter',
            old_name='serial',
            new_name='dev',
        ),
        migrations.RenameField(
            model_name='keezer',
            old_name='serial',
            new_name='dev',
        ),
    ]
