# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_auto_20160224_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fermenter',
            name='dev',
            field=models.CharField(blank=True, default=None, max_length=12),
        ),
        migrations.AlterField(
            model_name='keezer',
            name='dev',
            field=models.CharField(blank=True, default=None, max_length=12),
        ),
    ]
