# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fermenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=16)),
                ('dev', models.CharField(default='', max_length=12)),
                ('mode', models.CharField(choices=[('C', 'CHILL'), ('H', 'HEAT')], default='C', max_length=1)),
                ('setpoint', models.DecimalField(decimal_places=2, default=64.0, max_digits=5)),
                ('hysteresis', models.DecimalField(decimal_places=1, default=0.1, max_digits=2)),
                ('pumprun', models.IntegerField(default=5000)),
                ('pumpdelay', models.IntegerField(default=60000)),
            ],
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('datetime', models.DateTimeField()),
                ('fermenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fermenter.Fermenter')),
            ],
        ),
    ]
