# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-09 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fermenter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fermenter',
            name='mode',
            field=models.CharField(choices=[('0', 'CHILL'), ('1', 'HEAT')], default='C', max_length=1),
        ),
    ]
