# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fermenter', '0002_remove_fermenter_dev'),
    ]

    operations = [
        migrations.AddField(
            model_name='fermenter',
            name='tag',
            field=models.CharField(default='', max_length=16),
        ),
    ]
