# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-09 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fermenter', '0002_auto_20160409_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='fermenter',
            name='fid',
            field=models.IntegerField(default=0),
        ),
    ]
