# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-09 02:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fermenter', '0003_fermenter_fid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fermenter',
            old_name='tag',
            new_name='name',
        ),
    ]
