# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-09 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fermenter', '0004_auto_20160409_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fermenter',
            name='fid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fermenter',
            name='mode',
            field=models.CharField(choices=[('0', 'CHILL'), ('1', 'HEAT')], default='0', max_length=1),
        ),
    ]
