# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-13 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fermenter', '0005_auto_20160409_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fermenter',
            name='mode',
            field=models.CharField(choices=[('0', 'OFF'), ('1', 'CHILL'), ('2', 'HEAT')], default='0', max_length=1),
        ),
    ]
