# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-05 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fermenter', '0006_auto_20160413_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='fermenter',
            name='rampdelay',
            field=models.IntegerField(default=3600000),
        ),
        migrations.AddField(
            model_name='fermenter',
            name='ramppoint',
            field=models.DecimalField(decimal_places=2, default=64.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='fermenter',
            name='rampstep',
            field=models.DecimalField(decimal_places=1, default=0.1, max_digits=2),
        ),
    ]
