# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-05 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fermenter', '0007_auto_20160505_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fermenter',
            name='rampstep',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
